# Tomcat
server:
  port: 9999
##设置日志级别
logging:
  level:
    kcp: info
##spring:
#  application:
#    # 应用名称
#    name: ls-device
#  # 资源信息
#  messages:
#    basename: code/project
#  profiles:
#    # 环境配置
#    active: @activatedProperties@
#  cloud:
#    nacos:
#      username: @nacos.username@
#      password: @nacos.password@
#      discovery:
#        # 服务注册地址
#        server-addr: @nacosAddress@
#        namespace: @nacosNamespace@
#      config:
#        # 配置中心地址
#        server-addr:  @nacosAddress@
#        namespace: @nacosNamespace@
#        # 配置文件格式
#        file-extension: yml
#        # 共享配置
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
